[phases.setup]
nixPkgs = ["python310"]  # Use your required version here

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
